name: Version Bump Check

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

env:
  FILE_PATH: 'cmd/root.go'                                   # Path to file with version string
  VERSION_PATTERN: 'Version: "v[0-9]\+\.[0-9]\+\.[0-9]\+",'  # Version string regex pattern

jobs:
  version-check:
    if: ${{ !startsWith(github.event.pull_request.title, 'ci(actions):') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      with:
        fetch-depth: 2
    - name: Check if Version String is Updated
      run: |
        if git diff -U0 --diff-filter 'AM' -r HEAD^1 HEAD -- "$FILE_PATH" | grep -q "$VERSION_PATTERN"; then
          echo "##### ✅ Version updated in $FILE_PATH" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "##### ❌ Version NOT updated in $FILE_PATH" >> "$GITHUB_STEP_SUMMARY"
          exit 1
        fi
